[package]
name = "sum_of_squares"
version = "0.1.0"
authors = ["Evan Hyett <evan1hyett@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
